name: Build Qt CMake Project (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_DIR: C:\Qt\5.15.2\msvc2019_64
      VS_DIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
      BUILD_DIR: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Repository
        run: |
          cd QT_Car_Telltales_Cmake_Build\Scripts
          call Setup_Repo.bat
        shell: cmd

      - name: Setup Qt and Visual Studio Environment
        run: |
          call "%QT_DIR%\bin\qtenv2.bat"
          call "%VS_DIR%\VC\Auxiliary\Build\vcvarsall.bat" x64
        shell: cmd

      - name: Configure with CMake
        run: |
          cmake -S . -B "%BUILD_DIR%" -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="%QT_DIR%\lib\cmake"
        shell: cmd

      - name: Build with CMake
        run: |
          cmake --build "%BUILD_DIR%" --config Release
        shell: cmd

      - name: List Generated Files
        run: dir "%BUILD_DIR%\Release"
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QtTelltaleProject
          path: build/Release/*.exe
