name: Build Qt Car Telltales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  QT_DIR: C:\Qt\5.15.2\msvc2019_64
  VS_DIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
  BUILD_DIR: build

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4
      
      - name: Setup Repository
        shell: cmd
        run: |
          echo "Running setup repository batch script..."
          cd /d "${{ github.workspace }}\Scripts"
          call Setup_Repo.bat main
      
      - name: Setup Environment
        shell: cmd
        run: |
          echo "Setting up Qt and Visual Studio environment..."
          call "${{ env.QT_DIR }}\bin\qtenv2.bat"
          call "${{ env.VS_DIR }}\VC\Auxiliary\Build\vcvarsall.bat" x64
      
      - name: Clean
        shell: cmd
        run: |
          echo "Cleaning previous build files..."
          if exist "${{ github.workspace }}\${{ env.BUILD_DIR }}" rmdir /S /Q "${{ github.workspace }}\${{ env.BUILD_DIR }}"
          if exist "${{ github.workspace }}\CMakeCache.txt" del "${{ github.workspace }}\CMakeCache.txt"
      
      - name: CMake Configure
        shell: cmd
        run: |
          echo "Configuring CMake project..."
          cmake -S "${{ github.workspace }}" -B "${{ github.workspace }}\${{ env.BUILD_DIR }}" -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}\lib\cmake"
      
      - name: CMake Build
        shell: cmd
        run: |
          echo "Building project..."
          cmake --build "${{ github.workspace }}\${{ env.BUILD_DIR }}" --config Release
      
      - name: Run
        shell: cmd
        run: |
          echo "Running executable..."
          "${{ github.workspace }}\${{ env.BUILD_DIR }}\Release\QtTelltaleProject.exe"
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QtTelltaleProject
          path: ${{ env.BUILD_DIR }}\Release\QtTelltaleProject.exe
          retention-days: 30
      
      - name: Build Success
        if: success()
        run: echo "Build completed successfully!"
      
      - name: Build Failure
        if: failure()
        run: echo "Build failed. Check logs above for errors."
