name: Build Qt Car Telltales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4
      
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
      
      - name: Setup Repository
        shell: cmd
        run: |
          echo "Running setup repository batch script..."
          if exist "${{ github.workspace }}\Scripts\Setup_Repo.bat" (
            call "${{ github.workspace }}\Scripts\Setup_Repo.bat" main
          ) else (
            echo "Setup_Repo.bat not found, skipping..."
          )
      
      - name: Clean
        shell: cmd
        run: |
          echo "Cleaning previous build files..."
          if exist "${{ github.workspace }}\build" rmdir /S /Q "${{ github.workspace }}\build"
          if exist "${{ github.workspace }}\CMakeCache.txt" del "${{ github.workspace }}\CMakeCache.txt"
      
      - name: CMake Configure
        shell: cmd
        run: |
          echo "Configuring CMake project..."
          cmake -S "${{ github.workspace }}" -B "${{ github.workspace }}\build" -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="${{ env.Qt5_DIR }}\lib\cmake"
      
      - name: CMake Build
        shell: cmd
        run: |
          echo "Building project..."
          cmake --build "${{ github.workspace }}\build" --config Release
      
      - name: Build Success
        if: success()
        run: echo "✓ Build completed successfully!"
      
      - name: Build Failure
        if: failure()
        run: echo "✗ Build failed. Check logs above for errors."
