name: Build Qt Car Telltales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_DIR: C:\Qt\5.15.2\msvc2019_64
      VS_DIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
      BUILD_DIR: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify repo structure
      shell: cmd
      run: dir /b

    - name: Run setup repo script
      shell: cmd
      run: |
        cd /d "${{ github.workspace }}\Scripts"
        dir /b
        call Setup_Repo.bat

    - name: Setup Qt and Visual Studio environment
      shell: cmd
      run: |
        call "%QT_DIR%\bin\qtenv2.bat"
        call "%VS_DIR%\VC\Auxiliary\Build\vcvarsall.bat" x64

    - name: Configure CMake
      shell: cmd
      run: |
        cd /d "${{ github.workspace }}"
        cmake -S . -B %BUILD_DIR% -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="%QT_DIR%\lib\cmake"

    - name: Build project
      shell: cmd
      run: |
        cmake --build %BUILD_DIR% --config Release

    - name: List output files
      shell: cmd
      run: dir /b %BUILD_DIR%\Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtTelltaleProject
        path: build/Release/QtTelltaleProject.exe
