name: Build Qt Car Telltales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    env:
      QT_DIR: C:\Qt\5.15.2\msvc2019_64
      VS_DIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
      BUILD_DIR: build
    
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4
      
      - name: Check directory structure
        shell: cmd
        run: |
          echo "Current workspace:"
          cd /d "${{ github.workspace }}"
          dir /b
      
      - name: Setup Repository
        shell: cmd
        run: |
          echo "Running setup repository batch script..."
          if exist "${{ github.workspace }}\Scripts\Setup_Repo.bat" (
            cd /d "${{ github.workspace }}\Scripts"
            call Setup_Repo.bat main
          ) else (
            echo "Setup_Repo.bat not found. Skipping..."
          )
      
      - name: Setup Qt and Visual Studio
        shell: cmd
        run: |
          echo "Setting up Qt and Visual Studio environment..."
          if exist "${{ env.QT_DIR }}\bin\qtenv2.bat" (
            call "${{ env.QT_DIR }}\bin\qtenv2.bat"
          ) else (
            echo "Qt environment not found at ${{ env.QT_DIR }}"
          )
          if exist "${{ env.VS_DIR }}\VC\Auxiliary\Build\vcvarsall.bat" (
            call "${{ env.VS_DIR }}\VC\Auxiliary\Build\vcvarsall.bat" x64
          ) else (
            echo "Visual Studio environment not found at ${{ env.VS_DIR }}"
          )
      
      - name: Verify CMake
        shell: cmd
        run: cmake --version
      
      - name: Clean Build Directory
        shell: cmd
        run: |
          echo "Cleaning previous build files..."
          if exist "${{ github.workspace }}\${{ env.BUILD_DIR }}" rmdir /S /Q "${{ github.workspace }}\${{ env.BUILD_DIR }}"
          if exist "${{ github.workspace }}\CMakeCache.txt" del "${{ github.workspace }}\CMakeCache.txt"
      
      - name: CMake Configure
        shell: cmd
        run: |
          echo "Configuring CMake project..."
          cd /d "${{ github.workspace }}"
          cmake -S . -B ${{ env.BUILD_DIR }} -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}\lib\cmake"
      
      - name: CMake Build
        shell: cmd
        run: |
          echo "Building project..."
          cmake --build "${{ github.workspace }}\${{ env.BUILD_DIR }}" --config Release
      
      - name: List Output Files
        shell: cmd
        run: |
          echo "Listing build output..."
          if exist "${{ github.workspace }}\${{ env.BUILD_DIR }}\Release" (
            dir /b "${{ github.workspace }}\${{ env.BUILD_DIR }}\Release"
          ) else (
            echo "Release directory not found"
          )
      
      - name: Run Executable
        shell: cmd
        run: |
          echo "Running executable..."
          if exist "${{ github.workspace }}\${{ env.BUILD_DIR }}\Release\QtTelltaleProject.exe" (
            "${{ github.workspace }}\${{ env.BUILD_DIR }}\Release\QtTelltaleProject.exe"
          ) else (
            echo "Executable not found"
          )
      
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: QtTelltaleProject
          path: ${{ env.BUILD_DIR }}\Release\QtTelltaleProject.exe
          retention-days: 30
    
    post:
      always:
        - name: Build Result
          run: echo "Build workflow completed"
